-   repo: git://github.com/pre-commit/pre-commit-hooks.git
    sha: 003e43251aea1da33f2072f2365ec8b9ceaae070
    hooks:
    -   id: autopep8-wrapper
        args:
        - --in-place
        - --aggressive
        - --aggressive
        - --max-line-length=131
        - --ignore=W503
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: flake8
        args:
        - --ignore=W503
    -   id: name-tests-test
        files: ^test*/.+\.py$
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: git://github.com/asottile/reorder_python_imports.git
    sha: 3d86483455ab5bd06cc1069fdd5ac57be5463f10
    hooks:
    -   id: reorder-python-imports
        files: .*\.py$
        exclude: ^(yelp/vendor/|yelp/bootstrapped/).*\.py$
        language_version: python2.7
        args: [--remove-import, 'from __future__ import with_statement']
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    sha: 181a63c511691da58116fa19a7241956018660bc
    hooks:
    -   id: remove-tabs
